<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ciprian-ThinkPad-T570-W10DG" name="ODIN_VALIDATOR_APITEST.App1" tests="39" failures="2" timestamp="08 Oct 2019 15:09:19 GMT" time="78.801" errors="0">
  <testcase name="test1" time="2.241" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test2" time="0.884" classname="ODIN_VALIDATOR_APITEST.App1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at ODIN_VALIDATOR_APITEST.App1.test2(App1.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.804" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test4" time="0.856" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test5" time="11.487" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test6" time="8.563" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test7" time="2.718" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test8" time="1.559" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test9" time="3.448" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test10" time="2.098" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test11" time="1.650" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test12" time="1.844" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test13" time="1.894" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test14" time="2.070" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test15" time="1.238" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test16" time="1.457" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test17" time="1.467" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test18" time="1.358" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test19" time="1.274" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test20" time="1.213" classname="ODIN_VALIDATOR_APITEST.App1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at ODIN_VALIDATOR_APITEST.App1.test20(App1.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test20 -->
  <testcase name="test21" time="1.798" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test22" time="1.446" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test23" time="1.464" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test24" time="1.237" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test25" time="1.356" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test26" time="2.004" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test27" time="1.258" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test28" time="1.222" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test29" time="2.464" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test30" time="1.934" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test31" time="1.459" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test32" time="1.456" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test33" time="0.738" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test34" time="1.554" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test35" time="1.466" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test36" time="2.040" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test37" time="1.518" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test38" time="0.640" classname="ODIN_VALIDATOR_APITEST.App1"/>
  <testcase name="test39" time="1.624" classname="ODIN_VALIDATOR_APITEST.App1"/>
</testsuite> <!-- ODIN_VALIDATOR_APITEST.App1 -->
